<?xml version="1.0" encoding="UTF-8"?><testrun name="mainTest" project="Mjukvarutestning" tests="11" started="11" failures="1" errors="0" ignored="0">
  <testsuite name="tests.mainTest" time="0.23">
    <testcase name="test_diceValues" classname="tests.mainTest" time="0.007"/>
    <testcase name="Test_systemExit" classname="tests.mainTest" time="0.002"/>
    <testcase name="test_mock" classname="tests.mainTest" time="0.216">
      <failure>org.mockito.exceptions.verification.NeverWantedButInvoked: 
game.ThrowDices(5);
Never wanted here:
-&gt; at tests.mainTest.test_mock(mainTest.java:133)
But invoked here:
-&gt; at tests.mainTest.test_mock(mainTest.java:132)
&#13;
	at tests.mainTest.test_mock(mainTest.java:133)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.contrib.java.lang.system.ExpectedSystemExit$1.evaluate(ExpectedSystemExit.java:130)&#13;
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)&#13;
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_CheckDiceListSize" classname="tests.mainTest" time="0.001"/>
    <testcase name="test_resultOutput" classname="tests.mainTest" time="0.0"/>
    <testcase name="test_MenuChoiceExceptionTest_NotInteger" classname="tests.mainTest" time="0.001"/>
    <testcase name="test_numberOfDicesExceptionTest_LowValue" classname="tests.mainTest" time="0.0"/>
    <testcase name="test_numberOfDicesExceptionTest_HighValue" classname="tests.mainTest" time="0.001"/>
    <testcase name="test_MenuChoiceExceptionTest_NotInRange_TooHigh" classname="tests.mainTest" time="0.0"/>
    <testcase name="test_ThrowDiceMenu" classname="tests.mainTest" time="0.001"/>
    <testcase name="test_MenuChoiceExceptionTest_NotInRange_TooLow" classname="tests.mainTest" time="0.001"/>
  </testsuite>
</testrun>
